# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eef2a505624e9702cef99ab7e34945136053926a8bd2c62cccae1aae15bf6b8962b18c4ae1b3f6300a0aaa1d97bf0ab05ad8e484b5b855ba74489ed4b0f649d6

test:
  secret_key_base: a0f70d5273a743c7f0c065a449af1aad4fd3786e2ea3a6a647a5a32f18d0c3e7b55fd4b9920882de53c8ea19258ebb5dc456c35f5a82a1947df2df44bb5f92c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
